import { AgeGroups } from '@/src/constants/AgeGroups';
import { Book } from '@/src/types';

export const userStories = [
  {
    id: 1,
    title: 'The little frog in the pond',
    ageGroup: AgeGroups[1],
    stars: 4,
    background: 'orange',
  },
  {
    id: 2,
    title: 'Adventures of the sleepy koala',
    ageGroup: AgeGroups[2],
    stars: 5,
    background: 'pink',
  },
  {
    id: 3,
    title: 'Mystery of the missing acorns',
    ageGroup: AgeGroups[1],
    stars: 3,
    background: 'blue',
  },
  {
    id: 4,
    title: 'The curious kitten',
    ageGroup: AgeGroups[2],
    stars: 4,
    background: 'yellow',
  },
  {
    id: 5,
    title: "Journey to the rainbow's end",
    ageGroup: AgeGroups[3],
    stars: 5,
    background: 'pink',
  },
  {
    id: 6,
    title: 'The brave little toaster',
    ageGroup: AgeGroups[1],
    stars: 4,
    background: 'orange',
  },
  {
    id: 7,
    title: "The wizard's apprentice",
    ageGroup: AgeGroups[3],
    stars: 5,
    background: 'yellow',
  },
  {
    id: 8,
    title: 'Underwater escapades',
    ageGroup: AgeGroups[2],
    stars: 4,
    background: 'pink',
  },
  {
    id: 9,
    title: 'The lost dinosaur',
    ageGroup: AgeGroups[1],
    stars: 3,
    background: 'blue',
  },
  {
    id: 10,
    title: 'The night sky explorer',
    ageGroup: AgeGroups[3],
    stars: 5,
    background: 'orange',
  },
] as Book[];

export const userNotifications = {
  stories: [
    {
      id: 1,
      type: 'new-story',
      title: 'Cleaning the ocean with my friends',
      author: 'John Connor',
      seen: false,
    },
    {
      id: 2,
      type: 'new-story',
      title: 'Once upon a time in my bedroom',
      author: 'Sarah Griffin',
      seen: false,
    },
    {
      id: 3,
      type: 'new-reads',
      title: 'Vincent and the baby dragon',
      seen: false,
      ammount: 24,
    },
    {
      id: 4,
      type: 'new-story',
      title: 'My amazing spaceship',
      author: 'Michael Splitz',
      seen: false,
    },
    {
      id: 5,
      type: 'new-reads',
      title: 'The little frog in the pound',
      seen: false,
      ammount: 42,
    },
    {
      id: 6,
      type: 'book-shipped',
      title: 'Vincent goes to the moon',
      seen: false,
      date: '2 days ago',
    },
    {
      id: 7,
      type: 'new-story',
      title: 'Amazing intro to soup making',
      author: 'Agatha Davis',
      seen: true,
    },
    {
      id: 8,
      type: 'new-story',
      title: 'How to make friends',
      author: 'John John Florence',
      seen: true,
    },
    {
      id: 9,
      type: 'new-reads',
      title: 'The little frog in the pound',
      seen: true,
      ammount: 12,
    },
  ],
  comments: [
    {
      id: 1,
      type: 'new-comment',
      title: 'Vincent and the baby dragon',
      seen: false,
      ammount: 24,
    },
    {
      id: 2,
      type: 'new-comment',
      title: 'The little frog in the pound',
      seen: false,
      ammount: 42,
    },
    {
      id: 1,
      type: 'new-reply',
      title: 'Once upon a time in my bedroom',
      author: 'Sarah Griffin',
      seen: true,
    },
  ],
};
